Line Number,Record Type,Status,Details,Error
1,O,Failed,New Organization,Organization already exists: New Organization
2,D,Failed,Joe Driver (me@email.com),"Database error: (pymysql.err.IntegrityError) (1062, ""Duplicate entry '0' for key 'USERS.PRIMARY'"")
[SQL: INSERT INTO `USERS` (`USERNAME`, `PASS`, `USER_TYPE`, `FNAME`, `LNAME`, `EMAIL`, `CREATED_AT`, `POINTS`, `PHONE`, `LOCKED_REASON`, wants_point_notifications, wants_order_notifications, `IS_ACTIVE`, `FAILED_ATTEMPTS`, `LOCKOUT_TIME`, `RESET_TOKEN`, `RESET_TOKEN_CREATED_AT`, `IS_LOCKED_OUT`) VALUES (%(USERNAME)s, %(PASS)s, %(USER_TYPE)s, %(FNAME)s, %(LNAME)s, %(EMAIL)s, %(CREATED_AT)s, %(POINTS)s, %(PHONE)s, %(LOCKED_REASON)s, %(wants_point_notifications)s, %(wants_order_notifications)s, %(IS_ACTIVE)s, %(FAILED_ATTEMPTS)s, %(LOCKOUT_TIME)s, %(RESET_TOKEN)s, %(RESET_TOKEN_CREATED_AT)s, %(IS_LOCKED_OUT)s)]
[parameters: {'USERNAME': 'jdriver', 'PASS': '$2b$12$EHiz0SICt.md29Ek9EBXZuaCbFp59L6Fdsw6lIEfoEBb5uNbTGfbC', 'USER_TYPE': 'driver', 'FNAME': 'Joe', 'LNAME': 'Driver', 'EMAIL': 'me@email.com', 'CREATED_AT': datetime.datetime(2025, 10, 21, 11, 44, 19, 302086), 'POINTS': 0, 'PHONE': None, 'LOCKED_REASON': None, 'wants_point_notifications': 1, 'wants_order_notifications': 1, 'IS_ACTIVE': 1, 'FAILED_ATTEMPTS': 0, 'LOCKOUT_TIME': None, 'RESET_TOKEN': None, 'RESET_TOKEN_CREATED_AT': None, 'IS_LOCKED_OUT': 0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)"
2,D,Failed,"['D', 'New Organization', 'Joe', 'Driver', 'me@email.com']","(pymysql.err.IntegrityError) (1062, ""Duplicate entry '0' for key 'USERS.PRIMARY'"")
[SQL: INSERT INTO `USERS` (`USERNAME`, `PASS`, `USER_TYPE`, `FNAME`, `LNAME`, `EMAIL`, `CREATED_AT`, `POINTS`, `PHONE`, `LOCKED_REASON`, wants_point_notifications, wants_order_notifications, `IS_ACTIVE`, `FAILED_ATTEMPTS`, `LOCKOUT_TIME`, `RESET_TOKEN`, `RESET_TOKEN_CREATED_AT`, `IS_LOCKED_OUT`) VALUES (%(USERNAME)s, %(PASS)s, %(USER_TYPE)s, %(FNAME)s, %(LNAME)s, %(EMAIL)s, %(CREATED_AT)s, %(POINTS)s, %(PHONE)s, %(LOCKED_REASON)s, %(wants_point_notifications)s, %(wants_order_notifications)s, %(IS_ACTIVE)s, %(FAILED_ATTEMPTS)s, %(LOCKOUT_TIME)s, %(RESET_TOKEN)s, %(RESET_TOKEN_CREATED_AT)s, %(IS_LOCKED_OUT)s)]
[parameters: {'USERNAME': 'jdriver', 'PASS': '$2b$12$EHiz0SICt.md29Ek9EBXZuaCbFp59L6Fdsw6lIEfoEBb5uNbTGfbC', 'USER_TYPE': 'driver', 'FNAME': 'Joe', 'LNAME': 'Driver', 'EMAIL': 'me@email.com', 'CREATED_AT': datetime.datetime(2025, 10, 21, 11, 44, 19, 302086), 'POINTS': 0, 'PHONE': None, 'LOCKED_REASON': None, 'wants_point_notifications': 1, 'wants_order_notifications': 1, 'IS_ACTIVE': 1, 'FAILED_ATTEMPTS': 0, 'LOCKOUT_TIME': None, 'RESET_TOKEN': None, 'RESET_TOKEN_CREATED_AT': None, 'IS_LOCKED_OUT': 0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)"
3,S,Failed,Jill Sponsor (jill@mail.com),"Database error: (pymysql.err.IntegrityError) (1062, ""Duplicate entry '0' for key 'USERS.PRIMARY'"")
[SQL: INSERT INTO `USERS` (`USERNAME`, `PASS`, `USER_TYPE`, `FNAME`, `LNAME`, `EMAIL`, `CREATED_AT`, `POINTS`, `PHONE`, `LOCKED_REASON`, wants_point_notifications, wants_order_notifications, `IS_ACTIVE`, `FAILED_ATTEMPTS`, `LOCKOUT_TIME`, `RESET_TOKEN`, `RESET_TOKEN_CREATED_AT`, `IS_LOCKED_OUT`) VALUES (%(USERNAME)s, %(PASS)s, %(USER_TYPE)s, %(FNAME)s, %(LNAME)s, %(EMAIL)s, %(CREATED_AT)s, %(POINTS)s, %(PHONE)s, %(LOCKED_REASON)s, %(wants_point_notifications)s, %(wants_order_notifications)s, %(IS_ACTIVE)s, %(FAILED_ATTEMPTS)s, %(LOCKOUT_TIME)s, %(RESET_TOKEN)s, %(RESET_TOKEN_CREATED_AT)s, %(IS_LOCKED_OUT)s)]
[parameters: {'USERNAME': 'jsponsor', 'PASS': '$2b$12$DppSUneYD.VVHN/spfUFAemUqHX5SH6XTKa0J2QEX9YY/4ccQjqXS', 'USER_TYPE': 'sponsor', 'FNAME': 'Jill', 'LNAME': 'Sponsor', 'EMAIL': 'jill@mail.com', 'CREATED_AT': datetime.datetime(2025, 10, 21, 11, 44, 19, 687202), 'POINTS': 0, 'PHONE': None, 'LOCKED_REASON': None, 'wants_point_notifications': 1, 'wants_order_notifications': 1, 'IS_ACTIVE': 1, 'FAILED_ATTEMPTS': 0, 'LOCKOUT_TIME': None, 'RESET_TOKEN': None, 'RESET_TOKEN_CREATED_AT': None, 'IS_LOCKED_OUT': 0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)"
3,S,Failed,"['S', 'New Organization', 'Jill', 'Sponsor', 'jill@mail.com']","(pymysql.err.IntegrityError) (1062, ""Duplicate entry '0' for key 'USERS.PRIMARY'"")
[SQL: INSERT INTO `USERS` (`USERNAME`, `PASS`, `USER_TYPE`, `FNAME`, `LNAME`, `EMAIL`, `CREATED_AT`, `POINTS`, `PHONE`, `LOCKED_REASON`, wants_point_notifications, wants_order_notifications, `IS_ACTIVE`, `FAILED_ATTEMPTS`, `LOCKOUT_TIME`, `RESET_TOKEN`, `RESET_TOKEN_CREATED_AT`, `IS_LOCKED_OUT`) VALUES (%(USERNAME)s, %(PASS)s, %(USER_TYPE)s, %(FNAME)s, %(LNAME)s, %(EMAIL)s, %(CREATED_AT)s, %(POINTS)s, %(PHONE)s, %(LOCKED_REASON)s, %(wants_point_notifications)s, %(wants_order_notifications)s, %(IS_ACTIVE)s, %(FAILED_ATTEMPTS)s, %(LOCKOUT_TIME)s, %(RESET_TOKEN)s, %(RESET_TOKEN_CREATED_AT)s, %(IS_LOCKED_OUT)s)]
[parameters: {'USERNAME': 'jsponsor', 'PASS': '$2b$12$DppSUneYD.VVHN/spfUFAemUqHX5SH6XTKa0J2QEX9YY/4ccQjqXS', 'USER_TYPE': 'sponsor', 'FNAME': 'Jill', 'LNAME': 'Sponsor', 'EMAIL': 'jill@mail.com', 'CREATED_AT': datetime.datetime(2025, 10, 21, 11, 44, 19, 687202), 'POINTS': 0, 'PHONE': None, 'LOCKED_REASON': None, 'wants_point_notifications': 1, 'wants_order_notifications': 1, 'IS_ACTIVE': 1, 'FAILED_ATTEMPTS': 0, 'LOCKOUT_TIME': None, 'RESET_TOKEN': None, 'RESET_TOKEN_CREATED_AT': None, 'IS_LOCKED_OUT': 0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)"
4,D,Failed,"['D', 'This is', 'AN ERROR', 'x@y.com']",Insufficient data for driver record. Format: D|Organization|FirstName|LastName|Email
5,D,Failed,Tom Smith (tom887@gmail.com),"Database error: (pymysql.err.IntegrityError) (1062, ""Duplicate entry '0' for key 'USERS.PRIMARY'"")
[SQL: INSERT INTO `USERS` (`USERNAME`, `PASS`, `USER_TYPE`, `FNAME`, `LNAME`, `EMAIL`, `CREATED_AT`, `POINTS`, `PHONE`, `LOCKED_REASON`, wants_point_notifications, wants_order_notifications, `IS_ACTIVE`, `FAILED_ATTEMPTS`, `LOCKOUT_TIME`, `RESET_TOKEN`, `RESET_TOKEN_CREATED_AT`, `IS_LOCKED_OUT`) VALUES (%(USERNAME)s, %(PASS)s, %(USER_TYPE)s, %(FNAME)s, %(LNAME)s, %(EMAIL)s, %(CREATED_AT)s, %(POINTS)s, %(PHONE)s, %(LOCKED_REASON)s, %(wants_point_notifications)s, %(wants_order_notifications)s, %(IS_ACTIVE)s, %(FAILED_ATTEMPTS)s, %(LOCKOUT_TIME)s, %(RESET_TOKEN)s, %(RESET_TOKEN_CREATED_AT)s, %(IS_LOCKED_OUT)s)]
[parameters: {'USERNAME': 'tsmith', 'PASS': '$2b$12$tJe2Wxee5rBHhk5ehdgNwOo9Y2ZZkb/P88kV33TQgxQYOErTEC.mm', 'USER_TYPE': 'driver', 'FNAME': 'Tom', 'LNAME': 'Smith', 'EMAIL': 'tom887@gmail.com', 'CREATED_AT': datetime.datetime(2025, 10, 21, 11, 44, 20, 43974), 'POINTS': 0, 'PHONE': None, 'LOCKED_REASON': None, 'wants_point_notifications': 1, 'wants_order_notifications': 1, 'IS_ACTIVE': 1, 'FAILED_ATTEMPTS': 0, 'LOCKOUT_TIME': None, 'RESET_TOKEN': None, 'RESET_TOKEN_CREATED_AT': None, 'IS_LOCKED_OUT': 0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)"
5,D,Failed,"['D', 'Existing Organization', 'Tom', 'Smith', 'tom887@gmail.com']","(pymysql.err.IntegrityError) (1062, ""Duplicate entry '0' for key 'USERS.PRIMARY'"")
[SQL: INSERT INTO `USERS` (`USERNAME`, `PASS`, `USER_TYPE`, `FNAME`, `LNAME`, `EMAIL`, `CREATED_AT`, `POINTS`, `PHONE`, `LOCKED_REASON`, wants_point_notifications, wants_order_notifications, `IS_ACTIVE`, `FAILED_ATTEMPTS`, `LOCKOUT_TIME`, `RESET_TOKEN`, `RESET_TOKEN_CREATED_AT`, `IS_LOCKED_OUT`) VALUES (%(USERNAME)s, %(PASS)s, %(USER_TYPE)s, %(FNAME)s, %(LNAME)s, %(EMAIL)s, %(CREATED_AT)s, %(POINTS)s, %(PHONE)s, %(LOCKED_REASON)s, %(wants_point_notifications)s, %(wants_order_notifications)s, %(IS_ACTIVE)s, %(FAILED_ATTEMPTS)s, %(LOCKOUT_TIME)s, %(RESET_TOKEN)s, %(RESET_TOKEN_CREATED_AT)s, %(IS_LOCKED_OUT)s)]
[parameters: {'USERNAME': 'tsmith', 'PASS': '$2b$12$tJe2Wxee5rBHhk5ehdgNwOo9Y2ZZkb/P88kV33TQgxQYOErTEC.mm', 'USER_TYPE': 'driver', 'FNAME': 'Tom', 'LNAME': 'Smith', 'EMAIL': 'tom887@gmail.com', 'CREATED_AT': datetime.datetime(2025, 10, 21, 11, 44, 20, 43974), 'POINTS': 0, 'PHONE': None, 'LOCKED_REASON': None, 'wants_point_notifications': 1, 'wants_order_notifications': 1, 'IS_ACTIVE': 1, 'FAILED_ATTEMPTS': 0, 'LOCKOUT_TIME': None, 'RESET_TOKEN': None, 'RESET_TOKEN_CREATED_AT': None, 'IS_LOCKED_OUT': 0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)"
6,O,Failed,NewOrganization2,Organization already exists: NewOrganization2
7,D,Failed,New Driver (some@email.com),"Database error: (pymysql.err.IntegrityError) (1062, ""Duplicate entry '0' for key 'USERS.PRIMARY'"")
[SQL: INSERT INTO `USERS` (`USERNAME`, `PASS`, `USER_TYPE`, `FNAME`, `LNAME`, `EMAIL`, `CREATED_AT`, `POINTS`, `PHONE`, `LOCKED_REASON`, wants_point_notifications, wants_order_notifications, `IS_ACTIVE`, `FAILED_ATTEMPTS`, `LOCKOUT_TIME`, `RESET_TOKEN`, `RESET_TOKEN_CREATED_AT`, `IS_LOCKED_OUT`) VALUES (%(USERNAME)s, %(PASS)s, %(USER_TYPE)s, %(FNAME)s, %(LNAME)s, %(EMAIL)s, %(CREATED_AT)s, %(POINTS)s, %(PHONE)s, %(LOCKED_REASON)s, %(wants_point_notifications)s, %(wants_order_notifications)s, %(IS_ACTIVE)s, %(FAILED_ATTEMPTS)s, %(LOCKOUT_TIME)s, %(RESET_TOKEN)s, %(RESET_TOKEN_CREATED_AT)s, %(IS_LOCKED_OUT)s)]
[parameters: {'USERNAME': 'ndriver', 'PASS': '$2b$12$T/w70NTMuy1DQta/5Lkxi.kPd2PcDuX5sVndVQqIWZBhMkHxNyjNy', 'USER_TYPE': 'driver', 'FNAME': 'New', 'LNAME': 'Driver', 'EMAIL': 'some@email.com', 'CREATED_AT': datetime.datetime(2025, 10, 21, 11, 44, 20, 430199), 'POINTS': 0, 'PHONE': None, 'LOCKED_REASON': None, 'wants_point_notifications': 1, 'wants_order_notifications': 1, 'IS_ACTIVE': 1, 'FAILED_ATTEMPTS': 0, 'LOCKOUT_TIME': None, 'RESET_TOKEN': None, 'RESET_TOKEN_CREATED_AT': None, 'IS_LOCKED_OUT': 0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)"
7,D,Failed,"['D', 'Existing Organization', 'New', 'Driver', 'some@email.com']","(pymysql.err.IntegrityError) (1062, ""Duplicate entry '0' for key 'USERS.PRIMARY'"")
[SQL: INSERT INTO `USERS` (`USERNAME`, `PASS`, `USER_TYPE`, `FNAME`, `LNAME`, `EMAIL`, `CREATED_AT`, `POINTS`, `PHONE`, `LOCKED_REASON`, wants_point_notifications, wants_order_notifications, `IS_ACTIVE`, `FAILED_ATTEMPTS`, `LOCKOUT_TIME`, `RESET_TOKEN`, `RESET_TOKEN_CREATED_AT`, `IS_LOCKED_OUT`) VALUES (%(USERNAME)s, %(PASS)s, %(USER_TYPE)s, %(FNAME)s, %(LNAME)s, %(EMAIL)s, %(CREATED_AT)s, %(POINTS)s, %(PHONE)s, %(LOCKED_REASON)s, %(wants_point_notifications)s, %(wants_order_notifications)s, %(IS_ACTIVE)s, %(FAILED_ATTEMPTS)s, %(LOCKOUT_TIME)s, %(RESET_TOKEN)s, %(RESET_TOKEN_CREATED_AT)s, %(IS_LOCKED_OUT)s)]
[parameters: {'USERNAME': 'ndriver', 'PASS': '$2b$12$T/w70NTMuy1DQta/5Lkxi.kPd2PcDuX5sVndVQqIWZBhMkHxNyjNy', 'USER_TYPE': 'driver', 'FNAME': 'New', 'LNAME': 'Driver', 'EMAIL': 'some@email.com', 'CREATED_AT': datetime.datetime(2025, 10, 21, 11, 44, 20, 430199), 'POINTS': 0, 'PHONE': None, 'LOCKED_REASON': None, 'wants_point_notifications': 1, 'wants_order_notifications': 1, 'IS_ACTIVE': 1, 'FAILED_ATTEMPTS': 0, 'LOCKOUT_TIME': None, 'RESET_TOKEN': None, 'RESET_TOKEN_CREATED_AT': None, 'IS_LOCKED_OUT': 0}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)"
